In [1]:
import tensorflow as tf
import numpy as np


In [2]:
ary = np.array([[4, 6, 2, 7],
                [1, 4, 8, 9],
                [8, 2, 4, 3],
                [6, 2, 7, 1]])

tru = np.array([[0, 0, 0, 2],  # top 1
                [1, 0, 1, 1],  # top 1 and 2
                [0, 0, 1, 0],  # top 2
                [0, 1, 0, 1]]) # top 3


In [59]:
def in_top_k(tru, pred, k=2):
    with tf.Session() as sess:
        pred_var = tf.constant(pred)
        tru_var = tf.constant(tru)
        # Get top values and indices
        top_v, top_i = tf.nn.top_k(pred_var, k, sorted=True)
        tru_max = tru == tru.max(axis=1)[:, None]
        top_i = sess.run(top_i)
        print('tru_max:', tru_max)
        #print(top_i.transpose())
        #print('pred_max shape 0', pred_max.shape[0])
        print(np.arange(tru_max.shape[0]))
        #return tru_max[:, top_i.transpose()].transpose()        
        return tru_max[np.arange(tru_max.shape[0]), top_i.transpose()].transpose()

def _in_top_k(tru, pred, k=2):
    tops = in_top_k(tru, ary, k)
    return np.any((tops[:, :1]), axis=1)

In [60]:
# print('_in_top_k', _in_top_k(tru, ary, k=2))

tops = in_top_k(tru, ary, k=3)
print('tops:', tops)

# A correct category appeared amongst top 1
print(np.any((tops[:, :1]), axis=1))

# # A correct category appeared amongst top 2
# print(np.any((tops[:, :2]), axis=1))

# # A correct category appeared amongst top 3
# print(np.any((tops[:, :3]), axis=1))


('tru_max:', array([[False, False, False,  True],
       [ True, False,  True,  True],
       [False, False,  True, False],
       [False,  True, False,  True]]))
[0 1 2 3]
('tops:', array([[ True, False, False],
       [ True,  True, False],
       [False,  True, False],
       [False, False,  True]]))
[ True  True False False]


In [71]:
print(arr)

arr[[0, 1], [[0, 2], [1, 2]]]

idxs = [[0, 1, 2], [1, 2, 0]]
# arr[[0, 1, 2], idxs]
arr[np.arange(3), idxs]


[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[0, 4, 8],
       [1, 5, 6]])

In [55]:
arr[0, 1]

1

In [137]:
from keras import backend as K
import keras


In [138]:
def in_top_k2(tru, pred, k=2):
    pred_var = K.constant(pred)
    tru_var = K.constant(tru)
    # Get top values and indices
    top_v, top_i = tf.nn.top_k(pred_var, k, sorted=True)
    w_max = tru == tru.max(axis=1)[:, None]
    top_i = sess.run(top_i)
    return w_max[np.arange(w_max.shape[0]), top_i.transpose()].transpose()


In [139]:
tops = in_top_k2(tru, ary, k=3)


RuntimeError: Attempted to use a closed Session.