In [1]:
import numpy as np

In [24]:
a = np.eye(4)
a.shape
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [3]:
a.reshape((2, 2, 4))

array([[[1., 0., 0., 0.],
        [0., 1., 0., 0.]],

       [[0., 0., 1., 0.],
        [0., 0., 0., 1.]]])

In [4]:
a.reshape((2, 4, 2))

array([[[1., 0.],
        [0., 0.],
        [0., 1.],
        [0., 0.]],

       [[0., 0.],
        [1., 0.],
        [0., 0.],
        [0., 1.]]])

In [5]:
a.reshape((4, 2, 2))

array([[[1., 0.],
        [0., 0.]],

       [[0., 1.],
        [0., 0.]],

       [[0., 0.],
        [1., 0.]],

       [[0., 0.],
        [0., 1.]]])

In [6]:
a = np.array([0, 1, 2])
b = np.array([3, 4, 5])

In [7]:
np.concatenate((a, b))

array([0, 1, 2, 3, 4, 5])

In [8]:
a.shape

(3,)

In [9]:
np.stack((a, b), axis=0)

array([[0, 1, 2],
       [3, 4, 5]])

In [10]:
np.stack((a, b), axis=1)

array([[0, 3],
       [1, 4],
       [2, 5]])

In [11]:
a2 = a.reshape((1, 3))
b2 = b.reshape((1, 3))
np.stack((a2, b2), axis=0)

array([[[0, 1, 2]],

       [[3, 4, 5]]])

In [12]:
np.stack((a2, b2), axis=1)

array([[[0, 1, 2],
        [3, 4, 5]]])

In [13]:
np.stack((a2, b2), axis=2)

array([[[0, 3],
        [1, 4],
        [2, 5]]])

In [14]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
np.stack((x, y), axis=0)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [15]:
np.stack((x, y), axis=1)

array([[[1, 2],
        [5, 6]],

       [[3, 4],
        [7, 8]]])

In [16]:
np.stack((x, y), axis=2)

array([[[1, 5],
        [2, 6]],

       [[3, 7],
        [4, 8]]])

In [17]:
s = np.stack((x.transpose(), y.transpose()), axis=1)
s

array([[[1, 3],
        [5, 7]],

       [[2, 4],
        [6, 8]]])

In [18]:
s[0,:,:]

array([[1, 3],
       [5, 7]])

In [19]:
x = np.array([[[2]]])
y = np.array([[[3]]])
x.shape

(1, 1, 1)

In [20]:
np.stack((x, y), axis=0)

array([[[[2]]],


       [[[3]]]])

In [21]:
np.stack((x, y), axis=1)

array([[[[2]],

        [[3]]]])

In [22]:
np.stack((x, y), axis=2)

array([[[[2],
         [3]]]])

In [23]:
np.stack((x, y), axis=3)

array([[[[2, 3]]]])